topics:
- name    : joystick
  topic   : /ria_odo/teleop/cmd_vel_smooth
  timeout : 0.5
  priority: 100

- name    : navigation
  topic   : /ria_odo/move_base/cmd_vel
  timeout : 0.5
  priority: 50

- name    : external
  topic   : /ext/cmd_vel/smooth
  timeout : 0.5
  priority: 10

- name    : fs
  topic   : /FAILSAFE
  timeout : 0.5
  priority: 1

locks:
- name    : runstop
  topic   : riaodo_runstop
  timeout : 0.0    
  priority: 255
